# PROD_BUILD_PERSISTENT_V28: Fixed status code token array check logic to pass cloud database engines
import os
import sys
import subprocess
import random
import time
import threading

# Force install standard network components if missing inside the host machine
try:
    import sympy as sp
except ImportError:
    print("Core dependency 'sympy' missing. Installing automatically...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "sympy"])
    import sympy as sp

try:
    import requests
except ImportError:
    print("Core dependency 'requests' missing. Installing automatically...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "requests"])
    import requests

try:
    from flask import Flask, Response
    HAS_FLASK = True
except ImportError:
    HAS_FLASK = False
    print("Flask module not detected. Proceeding in headless mode...")

# Database Authentication Environment Routing Targets
SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")

def init_supabase_table():
    """Programmatically provisions a raw math log data tracking matrix structure if missing on Supabase."""
    if not SUPABASE_URL or not SUPABASE_KEY:
        return
    
    exec_url = f"{SUPABASE_URL.strip('/')}/rest/v1/rpc/exec_sql"
    headers = {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json"
    }
    
    sql_query = {
        "query": "CREATE TABLE IF NOT EXISTS math_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, calculation TEXT NOT NULL);"
    }
    try:
        requests.post(exec_url, headers=headers, json=sql_query)
    except Exception:
        pass

if HAS_FLASK:
    app = Flask(__name__)

    @app.route('/')
    def home():
        """Displays your active database size and statistics in real-time."""
        total_logs = 0
        if SUPABASE_URL and SUPABASE_KEY:
            try:
                query_url = f"{SUPABASE_URL.strip('/')}/rest/v1/math_logs?select=count"
                headers = {"apikey": SUPABASE_KEY, "Authorization": f"Bearer {SUPABASE_KEY}"}
                res = requests.get(query_url, headers=headers)
                if res.status_code == 200:
                    total_logs = res.json().get("count", 0)
            except Exception:
                pass

        html_dashboard = f"""
        <html>
            <head><title>Lumeni Autonomous Engine</title></head>
            <body style="font-family: monospace; padding: 40px; background: #111; color: #0f0;">
                <h2>🤖 Lumeni Math Core Status: ACTIVE</h2>
                <p>📍 Storage Method: Persistent Cloud Database (Render Sleep Proof)</p>
                <p>📈 Total Mathematical Assertions Saved: <strong>{total_logs} assertions</strong></p>
                <hr style="border-color: #0f0;">
                <p>👉 <a href="/download" style="color: #fff; font-weight: bold;">[CLICK HERE TO STREAM AND SAVE YOUR FULL KNOWLEDGE_BASE.TXT FILE]</a></p>
            </body>
        </html>
        """
        return html_dashboard, 200

    @app.route('/download')
    def download_file():
        """Streams every single historical math log stored in the cloud directly into your browser as a clean text document download."""
        if not SUPABASE_URL or not SUPABASE_KEY:
            return "Database credentials missing.", 500
            
        query_url = f"{SUPABASE_URL.strip('/')}/rest/v1/math_logs?select=calculation"
        headers = {"apikey": SUPABASE_KEY, "Authorization": f"Bearer {SUPABASE_KEY}"}
        
        try:
            res = requests.get(query_url, headers=headers)
            if res.status_code == 200:
                log_rows = res.json()
                text_content = "\n".join(row.get("calculation", "") for row in log_rows)
                return Response(
                    text_content,
                    mimetype="text/plain",
                    headers={f"Content-Disposition": "attachment;filename=knowledge_base.txt"}
                )
        except Exception as e:
            return f"Error building database data stream: {e}", 500
        return "Database file generation active.", 404

def save_to_supabase(new_logs_list):
    """Pipes logs straight through to external persistent databases, completely eliminating Render data deletion bugs."""
    if not SUPABASE_URL or not SUPABASE_KEY:
        print("❌ DB SYNC FAULT: Supabase credentials are empty or missing inside the environment variables!")
        return False
        
    write_url = f"{SUPABASE_URL.strip('/')}/rest/v1/math_logs"
    headers = {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=minimal"
    }
    
    payload = [{"calculation": log} for log in new_logs_list]
    
    try:
        response = requests.post(write_url, headers=headers, json=payload)
        
        status_string = str(response.status_code).strip()
        
        if status_string == "200" or status_string == "201":
            print(f"✅ DB SYNC SUCCESS: SECURELY LOCKED {len(new_logs_list)} ASSERTIONS INTO PERSISTENT CLOUD MEMORY CELLS!")
            return True
        else:
            init_supabase_table()
            requests.post(write_url, headers=headers, json=payload)
            print("🔄 Table mapping initialized. Writing assertions to clean dataset.")
            return True
    except Exception as e:
        print(f"❌ DATABASE PIPELINE FAULT ENCOUNTERED: {e}")
        return False

def generate_autonomous_math():
    """Generates complex, randomized mathematical entries using SymPy."""
    category = random.choice(["calculus", "matrix", "algebra"])
    x, y = sp.symbols('x y')
    
    if category == "calculus":
        operation = random.choice(["derivative", "integral", "limit"])
        coeff1 = random.randint(2, 9)
        coeff2 = random.randint(1, 5)
        power = random.randint(3, 6)
        
        if operation == "derivative":
            expr = coeff1 * x**power - coeff2 * sp.sin(x)
            ans = sp.diff(expr, x)
            return f"[CALCULUS - DERIVATIVE] d/dx({expr}) = {ans}"
        elif operation == "integral":
            expr = coeff1 * x**(power-2) + coeff2 * sp.exp(x)
            ans = sp.integrate(expr, x)
            return f"[CALCULUS - INTEGRAL] ∫({expr}) dx = {ans} + C"
        else:
            expr = sp.sin(coeff1 * x) / (coeff2 * x)
            ans = sp.limit(expr, x, 0)
            return f"[CALCULUS - LIMIT] lim(x->0) [{expr}] = {ans}"

    elif category == "matrix":
        operation = random.choice(["determinant", "inverse", "eigenvalues"])
        size_choices = (2, 3)
        size = random.choice(size_choices)
        
        M = sp.matrices.dense.randMatrix(size, size, min=-5, max=5)
        
        if operation == "determinant":
            return f"[MATRIX - DET] det({M.tolist()}) = {M.det()}"
        elif operation == "inverse" and M.det() != 0:
            return f"[MATRIX - INV] inv({M.tolist()}) = {M.inv().tolist()}"
        else:
            return f"[MATRIX - EIGEN] eigenvalues({M.tolist()}) = {M.eigenvals()}"

    else:  # algebra
        operation = random.choice(["expand", "factor", "roots"])
        r1, r2 = random.randint(-4, 4), random.randint(-4, 4)
        
        if operation == "expand":
            expr = (x + r1) * (y - r2) * (x + 2)
            return f"[ALGEBRA - EXPAND] ({expr}) = {sp.expand(expr)}"
        elif operation == "factor":
            poly = sp.expand((x - r1) * (x - r2))
            return f"[ALGEBRA - FACTOR] {poly} = {sp.factor(poly)}"
        else:
            poly = x**2 - (r1 + r2)*x + (r1 * r2)
            return f"[ALGEBRA - ROOTS] roots({poly} = 0) => {sp.solve(poly, x)}"

def lumeni_engine_loop():
    """Generates advanced math logs and batch syncs them to Supabase cloud memory cells."""
    print("Lumeni SymPy Engine initiated...")
    init_supabase_table()
    
    while True:
        batch_logs = []
        print("🔢 BACKGROUND WORKER: Commencing autonomous math compilation window...")
        
        for i in range(15):
            try:
                log_entry = generate_autonomous_math()
                timestamped_entry = f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] {log_entry}"
                batch_logs.append(timestamped_entry)
                print(f"   [Math Log {i+1}/15 Generated Successfully]")
                time.sleep(0.2) 
            except Exception as e:
                print(f"⚠️ Engine Processing Exception: {e}")

        if batch_logs:
            save_to_supabase(batch_logs)
        else:
            print("⚠️ Sync skipped: No clean calculations were generated.")
            
        print("Window completed. Pausing engine loop process for 60 seconds...")
        time.sleep(60)

if __name__ == '__main__':
    if HAS_FLASK:
        engine_thread = threading.Thread(target=lumeni_engine_loop, daemon=True)
        engine_thread.start()
        
        port = int(os.environ.get("PORT", 5000))
        app.run(host='0.0.0.0', port=port)
    else:
        lumeni_engine_loop()
